In [5]:
import numpy as np 

data = np.array((23, 342, 43))

print(data)

[ 23 342  43]


In [8]:
#1D array
import numpy as np

data2 = np.array([21, 32, 31, 30, 23, 32, 21])

print(data2)

[21 32 31 30 23 32 21]


In [16]:
#3d array
import numpy as np

data3 = np.array([[21, 32, 11, 32], [21, 32, 54, 34], [32, 32, 43, 32]])

print(data3)
print("\nDimension of the array: ",data3.ndim)

[[21 32 11 32]
 [21 32 54 34]
 [32 32 43 32]]

Dimension of the array:  2


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [27]:
import numpy as np

data4 = np.array([21, 32, 34], ndmin = 3)

print(data4)
print("Number of dimensions: ", data4.ndim)

[[[21 32 34]]]
Number of dimensions:  3
