In [5]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:5])

[1 2 3 4]


In [4]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(arr[3:])

[3 4 5 6 7 8]


In [6]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(arr[:2])

[0 1]


In [8]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(arr[-4:-1])

[5 6 7]


In [13]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

print(arr[1:14:2])

[ 1  3  5  7  9 11 13]


In [14]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

print(arr[::2])

[ 0  2  4  6  8 10 12 14]


In [17]:
import numpy as np

arr = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])

print(arr[1, 1:5:2])

[1 3]
