In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

for x in arr:
    print(x)

1
2
3
4
5


In [5]:
import numpy as np

arrString = np.array(['hello', 'world!', 'how', 'are', 'you?'])

for y in arrString:
    print(y)

hello
world!
how
are
you?


In [6]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr2d:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
import numpy as np

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr3d:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [9]:
import numpy as np

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
