In [5]:
#joining 1d array
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

finalArr = np.concatenate((arr1, arr2))

print(finalArr)

[1 2 3 4 5 6]


In [10]:
#joining 2d array
import numpy as np

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

finalArr2d = np.concatenate((arr3, arr4), axis=1)

print(finalArr2d)

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
#Joining Arrays Using Stack Functions
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
#Stacking Along Rows - horizontal stack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [13]:
#Stacking Along Columns - vertical stack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
#Stacking Along Height (depth)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
