In [3]:
import numpy as np

arr = np.array([3, 1, 4, 5, 6, 8, 4, 2])

x = np.where(arr == 4)

print(x)

(array([2, 6], dtype=int64),)


In [4]:
import numpy as np

arr = np.array([3, 1, 4, 5, 6, 8, 4, 2])

x = np.where(arr%2 == 0)

print(x)

(array([2, 4, 5, 6, 7], dtype=int64),)


In [5]:
import numpy as np

arr = np.array([3, 1, 4, 5, 6, 8, 4, 2])

x = np.where(arr%2 == 1)

print(x)

(array([0, 1, 3], dtype=int64),)


In [11]:
#Search Sorted
import numpy as np

arr = np.array([5, 6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

2


In [24]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [26]:
#Multiple Values
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6, 8])

print(x)

[1 2 3 4]
