In [1]:
import numpy as np

myArray = np.array([4, 5, 2, 1, 0, 6, 9])

print(np.sort(myArray))

[0 1 2 4 5 6 9]


In [3]:
import numpy as np

myArrayString = np.array(['Banana', 'Apple', 'Grape', 'Pineapple', 'Coconut', 'Nut', 'Cherry'])

print(np.sort(myArrayString))

['Apple' 'Banana' 'Cherry' 'Coconut' 'Grape' 'Nut' 'Pineapple']


In [4]:
import numpy as np

myArrayString = np.array([False, True, False, True])

print(np.sort(myArrayString))

[False False  True  True]


In [6]:
import numpy as np

myArray = np.array([[4, 5, 2], [9, 6, 4]])

print(np.sort(myArray))

[[2 4 5]
 [4 6 9]]
