In [6]:
import numpy as np

myArray = np.array([34, 54, 65, 76, 12, 34])

x = [True, False, False, True, False, True]

newArray = myArray[x]

print(newArray)

[34 76 34]


In [10]:
import numpy as np

arr = np.array([4, 5, 6, 7, 8])

#created an empty list
filter_arr = []

#filtering the array and putting into the list
for element in arr:
    if element > 5:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newArr = arr[filter_arr]

print(filter_arr)
print(newArr)

[False, False, True, True, True]
[6 7 8]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [12]:
import numpy as np

arr = np.array([2, 3, 4, 1, 3, 5, 6])

filter_arr = arr > 3

newArr = arr[filter_arr]

print(filter_arr)
print(newArr)

[False False  True False False  True  True]
[4 5 6]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
