In [1]:
#NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [2]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [4]:
import numpy as np

arr = np.array([0, 90, 180, 270, 360])

x = np.deg2rad(arr)
print(x)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


In [5]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [ ]:
Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [6]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [7]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [ ]:
Hypotenues
Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [3]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
