In [3]:
import numpy as np

arr = np.array([2, 2, 3, 4, 5, 1, 1, 6])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

x = np.union1d(arr1, arr2)

print(x)

[1 2 3 4 5 6]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

x = np.intersect1d(arr1, arr2, assume_unique=True)

print(x)

[3 4]


In [8]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

x = np.setdiff1d(arr1, arr2, assume_unique=True)

print(x)

[1 2]


In [ ]:
#the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

In [12]:
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
